name: gocoverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  generate-coverage:
    runs-on: ubuntu-20.04
    steps:
      - name: Update coverage report
        uses: ncruces/go-coverage-report@v0
        with:
          report: true
          chart: true
          amend: true
